services:

  geoserver:
    # network_mode: host
    image: ${GEOSERVER_DOCKER_IMAGE_NAME}:${GEOSERVER_VERSION}
    container_name: "geoserver-local"
    env_file: .env
    volumes:
      - "./data:/opt/geoserver_data"
      - "./config:/opt/config"
    ports:
      - "8081:8080"
